config/routes.rb
Rails.application.routes.draw do

	root 'chats#index'

  resources :users, only:[:new, :create] do
  	resources :chats, only:[:index, :create, :show]
  end 
  resources :sessions, only:[:new, :destroy, :create]
	resources :messages, only:[:create]

    # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :subscriptions
  has_many :users, through: :subscriptions

  validates :identifier, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :chat
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :messages
	has_many :subscriptions
	has_many :chats, through: :subscriptions

	def existing_chats_users
		existing_chat_users = []
		chats.each do |chat| 
  		chat.subscriptions.each do |subscription|
  			existing_chat_users << subscription.user if subscription.user != self
  		end
  	end
  	existing_chat_users
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include UsersHelper
end

app/controllers/chats_controller.rb
require 'securerandom'

class ChatsController < ApplicationController
	before_action :require_login
  def index
  	chats = current_user.chats
  	@existing_chats_users = current_user.existing_chats_users
  end

  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chat_path(current_user, @chat,  :other_user => @other_user.id) 
  end


  def show
    @other_user = User.find(params[:other_user])
    @chat = Chat.find_by(id: params[:id])
    @message = Message.new
  end

 	private
  def find_chat(second_user)
    chats = current_user.chats
    chats.each do |chat|
      chat.subscriptions.each do |s|
        if s.user_id == second_user.id
          return chat
        end
      end
    end
    nil
  end

  def require_login
  	redirect_to new_session_path unless logged_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = Message.new(message_params)
    message.user = current_user

    if message.save
      ActionCable.server.broadcast( "messages_#{message_params[:chat_id]}",
      #broadcasting out to messages channel, which all chats are linked to messages channel
      message: message.content,
      user: message.user.username
      )
    else
      redirect_to chats_path
    end
  end

  private
    def message_params
      params.require(:message).permit(:content, :chat_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if !logged_in?
      @user = User.new
      render 'new'
    end

	end

  def create
    @user = User.find_by(username: login_params[:username])
    if @user && @user.authenticate(login_params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @error = "Invalid username or password"
      render 'new'
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
	end

	private  
  def login_params
    params.require(:user).permit(:username, :password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		@cached_user = @cached_user || User.find_by(id:session[:user_id])
	end

	def logged_in?
		current_user != nil
	end

end

app/helpers/users_helpers.rb
module UsersHelpers
	def current_user
		@cached_user = @cached_user || User.find_by(id:session[:user_id])
	end

	def logged_in?
		current_user != nil
	end

end

app/views/chats/index.html.erb
<div class="inline-block">
	List of current chats:
	<ul>
		<% if @existing_chats_users %>
		  <% @existing_chats_users.each do |other_user| %>
		  	<% if other_user != current_user %>
			    <li>
			      <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
			      <%= other_user.username %>
			      <% end %>
			    </li>
		    <% end %>
		  <% end %>
	  <% end %>
	</ul>
</div>

<div class="inline-block">
	All Users:
	<ul>
	  <% User.all.each do |other_user| %>
	  	<% if other_user != current_user %>
		    <li>
		      <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
		      <%= other_user.username %>
		      <% end %>
		    </li>
	    <% end %>
	  <% end %>
	</ul>
</div>
<%= link_to "Logout", session_path(current_user.id), method: :delete  %>

app/views/chats/show.html.erb
<div class="scroll">
  <h4>Chat with <%= @other_user.username %></h4>
  <% if @chat.messages.any? %>
    <div id="messages">
      <%= render partial: 'messages/message', collection: @chat.messages.order(id: :asc)%>
    </div>
  <%else%>
    <div id="messages">
    </div>
  <%end%>
</div>

<%= render partial: 'messages/message_form', locals: {message: @message, chat: @chat}%>

<p><%= link_to "Back to list of chats", user_chats_path(current_user.id) %></p>

<script>
  createMessageChannel();
  messageForm();
  //defaults scrolling to bottom
  $(".scroll").scrollTop($(".scroll")[0].scrollHeight);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Live Messaging Demo</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h3>Live Messaging Demo via Rails 5 ActionCable</h3>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<p><strong><%= message.user.username %>:</strong> <%=message.content%></p>

app/views/messages/_message_form.html.erb
<%=form_for message, remote: true,authenticity_token: true do |f|%>
  <%= f.text_area :content, data: {textarea: "message"}, placeholder: "Enter to Send"%>

  <%= f.hidden_field :chat_id, value: chat.id %>
<%end%>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>